---
- name: Install BCM 11 on RHEL 9.6:
  hosts: head_node
  become: yes
  gather_facts: yes
  collections:
    - brightcomputing.installer110
  
  roles:
    - role: brightcomputing.installer110.head_node
