---
product_key: 158246-841820-109190-867936-127764

license:
  country: US
  state: Colorado
  locality: Denver
  organization: Dell Technologies
  organizational_unit: DellHPC
  cluster_name: JASH-Cluster
  mac: "{{ ansible_default_ipv4.macaddress }}"

db_cmd_password: Dellsvcs1
slurm_user_pass: Dellsvcs1
ldap_root_pass: Dellsvcs1
ldap_readonly_pass: Dellsvcs1

mysql_login_user: root
mysql_login_password: Dellsvcs1
